### ISSUE TITLE
Refer friends to join Pi Network

### ISSUE THREAD

**Issue by Quantum004** [phodal/developer#11]
Pi is a new digital currency developed by Stanford PhDs, with over 47 million members worldwide. To claim your Pi, follow this link https://minepi.com/Quant2020 and use my username (Quant2020) as your invitation code.

**Comment by ayidaweiwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
